[package]
name = "slime_simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
bevy_shader_utils = "0.3.0"
bytemuck = "1.12.2"
rand = "0.8.5"
